#
#	Makefile for 'EmACT tools' (c) C. Jullien 	04/14/1996
#

#	-D_ISO			For ISO/IEC 9899:1990 C Compilers

#	Tools:

CC	= cc
LD	= cc

#	Flags:

DEFS	= -D_ISO
CFLAGS	= -O $(DEFS)

all: emgrep emtags diffh

emgrep:	grep.c
	@echo $*
	@$(CC) $(CFLAGS) -o emgrep grep.c

emtags:	ctags.c
	@echo $*
	@$(CC) $(CFLAGS) -o emtags ctags.c

diffh:	diffh.c
	@echo $*
	@$(CC) $(CFLAGS) -o diffh diffh.c

clean:
	@-rm *.o
	@-rm *.BAK
	@-rm core
